/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Punto2;


import java.awt.BorderLayout;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;

/**
 *
 * @author Usuario
 */
public class Impresiondata extends javax.swing.JFrame {

     private JList<String> Listmostrar;
    private JLabel lblCantidad;
    public Impresiondata(List<Vehiculo> carros, List<Vehiculo> motos, List<Vehiculo> bicis) {
        setTitle("Impresión de datos");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setBounds(100, 100, 400, 300);
       DefaultListModel<String> modelo = new DefaultListModel<>();
        for (Vehiculo carro : carros) {
            modelo.addElement(carro.getPlaca() + " - " + carro.getTipo() + " - " + carro.getHoraLlegada() + " - " + carro.getNumeroIngreso() + " - " + carro.getValor());
        }
        for (Vehiculo moto : motos) {
            modelo.addElement(moto.getPlaca() + " - " + moto.getTipo() + " - " + moto.getHoraLlegada() + " - " + moto.getNumeroIngreso() + " - " + moto.getValor());
        }
        for (Vehiculo bici : bicis) {
            modelo.addElement(bici.getPlaca() + " - " + bici.getTipo() + " - " + bici.getHoraLlegada() + " - " + bici.getNumeroIngreso() + " - " + bici.getValor());
        }
        Listmostrar = new JList<>(modelo);
        JScrollPane scrollPane = new JScrollPane(Listmostrar);
        getContentPane().add(scrollPane, BorderLayout.CENTER);
        int cantidadTotal = carros.size() + motos.size() + bicis.size();
        lblCantidad = new JLabel("Cantidad total de vehículos: " + cantidadTotal);
        getContentPane().add(lblCantidad, BorderLayout.SOUTH);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impresiondata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impresiondata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impresiondata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impresiondata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impresiondata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
